
package abenali.edu.proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveService", targetNamespace = "http://webservice.edu.abenali/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveService {


    /**
     * 
     * @param arg0
     * @return
     *     returns abenali.edu.proxy.Releve
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReleve", targetNamespace = "http://webservice.edu.abenali/", className = "abenali.edu.proxy.GetReleve")
    @ResponseWrapper(localName = "getReleveResponse", targetNamespace = "http://webservice.edu.abenali/", className = "abenali.edu.proxy.GetReleveResponse")
    @Action(input = "http://webservice.edu.abenali/ReleveService/getReleveRequest", output = "http://webservice.edu.abenali/ReleveService/getReleveResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://webservice.edu.abenali/ReleveService/getReleve/Fault/JAXBException")
    })
    public Releve getReleve(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws JAXBException_Exception
    ;

}
